// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: api/chat/v1/chat.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationChatServiceGetMessages = "/api.chat.v1.ChatService/GetMessages"
const OperationChatServiceMarkAsRead = "/api.chat.v1.ChatService/MarkAsRead"
const OperationChatServiceSendMessage = "/api.chat.v1.ChatService/SendMessage"

type ChatServiceHTTPServer interface {
	// GetMessages Get messages for a room
	GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
	// MarkAsRead Mark message as read
	MarkAsRead(context.Context, *MarkAsReadRequest) (*MarkAsReadResponse, error)
	// SendMessage Send a message
	SendMessage(context.Context, *SendMessageRequest) (*Message, error)
}

func RegisterChatServiceHTTPServer(s *http.Server, srv ChatServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/messages", _ChatService_SendMessage0_HTTP_Handler(srv))
	r.GET("/api/v1/rooms/{room_id}/messages", _ChatService_GetMessages0_HTTP_Handler(srv))
	r.POST("/api/v1/messages/{message_id}/read", _ChatService_MarkAsRead0_HTTP_Handler(srv))
}

func _ChatService_SendMessage0_HTTP_Handler(srv ChatServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendMessageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatServiceSendMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendMessage(ctx, req.(*SendMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Message)
		return ctx.Result(200, reply)
	}
}

func _ChatService_GetMessages0_HTTP_Handler(srv ChatServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMessagesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatServiceGetMessages)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMessages(ctx, req.(*GetMessagesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMessagesResponse)
		return ctx.Result(200, reply)
	}
}

func _ChatService_MarkAsRead0_HTTP_Handler(srv ChatServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MarkAsReadRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatServiceMarkAsRead)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MarkAsRead(ctx, req.(*MarkAsReadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MarkAsReadResponse)
		return ctx.Result(200, reply)
	}
}

type ChatServiceHTTPClient interface {
	// GetMessages Get messages for a room
	GetMessages(ctx context.Context, req *GetMessagesRequest, opts ...http.CallOption) (rsp *GetMessagesResponse, err error)
	// MarkAsRead Mark message as read
	MarkAsRead(ctx context.Context, req *MarkAsReadRequest, opts ...http.CallOption) (rsp *MarkAsReadResponse, err error)
	// SendMessage Send a message
	SendMessage(ctx context.Context, req *SendMessageRequest, opts ...http.CallOption) (rsp *Message, err error)
}

type ChatServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewChatServiceHTTPClient(client *http.Client) ChatServiceHTTPClient {
	return &ChatServiceHTTPClientImpl{client}
}

// GetMessages Get messages for a room
func (c *ChatServiceHTTPClientImpl) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...http.CallOption) (*GetMessagesResponse, error) {
	var out GetMessagesResponse
	pattern := "/api/v1/rooms/{room_id}/messages"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationChatServiceGetMessages))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// MarkAsRead Mark message as read
func (c *ChatServiceHTTPClientImpl) MarkAsRead(ctx context.Context, in *MarkAsReadRequest, opts ...http.CallOption) (*MarkAsReadResponse, error) {
	var out MarkAsReadResponse
	pattern := "/api/v1/messages/{message_id}/read"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationChatServiceMarkAsRead))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SendMessage Send a message
func (c *ChatServiceHTTPClientImpl) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...http.CallOption) (*Message, error) {
	var out Message
	pattern := "/api/v1/messages"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationChatServiceSendMessage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationRoomServiceCreateRoom = "/api.chat.v1.RoomService/CreateRoom"
const OperationRoomServiceGetRoom = "/api.chat.v1.RoomService/GetRoom"
const OperationRoomServiceJoinRoom = "/api.chat.v1.RoomService/JoinRoom"
const OperationRoomServiceLeaveRoom = "/api.chat.v1.RoomService/LeaveRoom"
const OperationRoomServiceListRooms = "/api.chat.v1.RoomService/ListRooms"

type RoomServiceHTTPServer interface {
	// CreateRoom Create a new room
	CreateRoom(context.Context, *CreateRoomRequest) (*Room, error)
	// GetRoom Get room details
	GetRoom(context.Context, *GetRoomRequest) (*Room, error)
	// JoinRoom Join a room
	JoinRoom(context.Context, *JoinRoomRequest) (*JoinRoomResponse, error)
	// LeaveRoom Leave a room
	LeaveRoom(context.Context, *LeaveRoomRequest) (*LeaveRoomResponse, error)
	// ListRooms List user's rooms
	ListRooms(context.Context, *ListRoomsRequest) (*ListRoomsResponse, error)
}

func RegisterRoomServiceHTTPServer(s *http.Server, srv RoomServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/rooms", _RoomService_CreateRoom0_HTTP_Handler(srv))
	r.GET("/api/v1/rooms/{id}", _RoomService_GetRoom0_HTTP_Handler(srv))
	r.GET("/api/v1/users/{user_id}/rooms", _RoomService_ListRooms0_HTTP_Handler(srv))
	r.POST("/api/v1/rooms/{room_id}/join", _RoomService_JoinRoom0_HTTP_Handler(srv))
	r.POST("/api/v1/rooms/{room_id}/leave", _RoomService_LeaveRoom0_HTTP_Handler(srv))
}

func _RoomService_CreateRoom0_HTTP_Handler(srv RoomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateRoomRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoomServiceCreateRoom)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateRoom(ctx, req.(*CreateRoomRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Room)
		return ctx.Result(200, reply)
	}
}

func _RoomService_GetRoom0_HTTP_Handler(srv RoomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRoomRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoomServiceGetRoom)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRoom(ctx, req.(*GetRoomRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Room)
		return ctx.Result(200, reply)
	}
}

func _RoomService_ListRooms0_HTTP_Handler(srv RoomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRoomsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoomServiceListRooms)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRooms(ctx, req.(*ListRoomsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRoomsResponse)
		return ctx.Result(200, reply)
	}
}

func _RoomService_JoinRoom0_HTTP_Handler(srv RoomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in JoinRoomRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoomServiceJoinRoom)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.JoinRoom(ctx, req.(*JoinRoomRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*JoinRoomResponse)
		return ctx.Result(200, reply)
	}
}

func _RoomService_LeaveRoom0_HTTP_Handler(srv RoomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LeaveRoomRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoomServiceLeaveRoom)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LeaveRoom(ctx, req.(*LeaveRoomRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LeaveRoomResponse)
		return ctx.Result(200, reply)
	}
}

type RoomServiceHTTPClient interface {
	// CreateRoom Create a new room
	CreateRoom(ctx context.Context, req *CreateRoomRequest, opts ...http.CallOption) (rsp *Room, err error)
	// GetRoom Get room details
	GetRoom(ctx context.Context, req *GetRoomRequest, opts ...http.CallOption) (rsp *Room, err error)
	// JoinRoom Join a room
	JoinRoom(ctx context.Context, req *JoinRoomRequest, opts ...http.CallOption) (rsp *JoinRoomResponse, err error)
	// LeaveRoom Leave a room
	LeaveRoom(ctx context.Context, req *LeaveRoomRequest, opts ...http.CallOption) (rsp *LeaveRoomResponse, err error)
	// ListRooms List user's rooms
	ListRooms(ctx context.Context, req *ListRoomsRequest, opts ...http.CallOption) (rsp *ListRoomsResponse, err error)
}

type RoomServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewRoomServiceHTTPClient(client *http.Client) RoomServiceHTTPClient {
	return &RoomServiceHTTPClientImpl{client}
}

// CreateRoom Create a new room
func (c *RoomServiceHTTPClientImpl) CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...http.CallOption) (*Room, error) {
	var out Room
	pattern := "/api/v1/rooms"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRoomServiceCreateRoom))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRoom Get room details
func (c *RoomServiceHTTPClientImpl) GetRoom(ctx context.Context, in *GetRoomRequest, opts ...http.CallOption) (*Room, error) {
	var out Room
	pattern := "/api/v1/rooms/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRoomServiceGetRoom))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// JoinRoom Join a room
func (c *RoomServiceHTTPClientImpl) JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...http.CallOption) (*JoinRoomResponse, error) {
	var out JoinRoomResponse
	pattern := "/api/v1/rooms/{room_id}/join"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRoomServiceJoinRoom))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LeaveRoom Leave a room
func (c *RoomServiceHTTPClientImpl) LeaveRoom(ctx context.Context, in *LeaveRoomRequest, opts ...http.CallOption) (*LeaveRoomResponse, error) {
	var out LeaveRoomResponse
	pattern := "/api/v1/rooms/{room_id}/leave"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRoomServiceLeaveRoom))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListRooms List user's rooms
func (c *RoomServiceHTTPClientImpl) ListRooms(ctx context.Context, in *ListRoomsRequest, opts ...http.CallOption) (*ListRoomsResponse, error) {
	var out ListRoomsResponse
	pattern := "/api/v1/users/{user_id}/rooms"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRoomServiceListRooms))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
