// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/yourusername/chat-app/internal/biz"
	"github.com/yourusername/chat-app/internal/conf"
	"github.com/yourusername/chat-app/internal/data"
	"github.com/yourusername/chat-app/internal/server"
	"github.com/yourusername/chat-app/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	bizUserRepo := data.NewUserRepoAdapter(userRepo, logger)
	jwtTokenManager := biz.NewJWTTokenManagerFromConfig(auth)
	bcryptPasswordHasher := biz.NewBcryptPasswordHasher()
	userUseCase := biz.NewUserUseCase(bizUserRepo, jwtTokenManager, bcryptPasswordHasher, logger)
	userService := service.NewUserService(userUseCase, logger)
	roomRepo := data.NewRoomRepo(dataData, logger)
	bizRoomRepo := data.NewRoomRepoAdapter(roomRepo, logger)
	roomUseCase := biz.NewRoomUseCase(bizRoomRepo, bizUserRepo, logger)
	roomService := service.NewRoomService(roomUseCase, logger)
	messageRepo := data.NewMessageRepo(dataData, logger)
	chatRepo := data.NewChatRepoAdapter(messageRepo, logger)
	chatUseCase := biz.NewChatUseCase(chatRepo, bizRoomRepo, bizUserRepo, logger)
	chatService := service.NewChatService(chatUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, auth, userService, roomService, chatService, logger)
	client := data.NewRedisClient(dataData)
	httpServer := server.NewHTTPServer(confServer, auth, userService, roomService, chatService, client, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
